name: HappyDog
main: com.github.JohnGuru.HappyDog.HappyDog
version: 1.1
description: Manage properties of pets
author: JohnGuru
authors: [RoyCurtis]
commands:
  hdowner:
    description: updates the Tameable's owner
    usage: /<command> <playername>
  hdfree:
    description: resets the Tameable to unowned/wild condition
    usage: /<command>
