name:        ${project.artifactId}
version:     ${project.version}
description: ${project.description}
authors:     [JohnGuru, RoyCurtis]
main:        happypet.HappyPet

commands:
  happypet:
    description: Manages properties of pets
    usage: |
      • /<command> owner [player] - Changes owner of a pet
      • /<command> calm - Calms an angered pet wolf
      • /<command> free - Frees a pet into the wild
      • /<command> wand - Find out what the pet wand is set to
      • /<command> reload - Reloads config file

permissions:
  happypet.player:
    description: |
      Gives all typical player permissions, which are:
      • happypet.owner
      • happypet.calm
      • happypet.free
      • happypet.wand
    children:
      happypet.owner: true
      happypet.calm: true
      happypet.free: true
      happypet.wand: true

  happypet.admin:
    description: |
      Gives all typical player and admin permissions, which are:
      • happypet.owner
      • happypet.owner.any
      • happypet.calm
      • happypet.calm.any
      • happypet.free
      • happypet.free.any
      • happypet.wand
      • happypet.reload
    children:
      happypet.owner.any: true
      happypet.calm.any: true
      happypet.free.any: true
      happypet.wand: true
      happypet.reload: true

  happypet.owner:
    description: Allows you to change the owner of your pet
    default: op

  happypet.owner.any:
    description: Allows you to change the owner of any pet
    default: op
    children:
      happypet.owner: true

  happypet.calm:
    description: Allows you to calm your angry pet wolf
    default: op

  happypet.calm.any:
    description: Allows you to calm any angry pet wolf
    default: op
    children:
      happypet.calm: true

  happypet.free:
    description: Allows you to free your pet into the wild
    default: op

  happypet.free.any:
    description: Allows you to free any pet into the wild
    default: op
    children:
      happypet.free: true

  happypet.wand:
    description: Allows you to use the pet information wand
    default: op

  happypet.reload:
    description: Allows you to reload the config file
    default: op