name: HappyDog
main: com.github.JohnGuru.HappyDog.HappyDog
version: 1.0
description: Modify Animal Properties 
author: JohnGuru
commands:
  hdowner:
    description: updates the Tameable's owner
    usage: /<command> <playername>
  hdfree:
    description: resets the Tameable to unowned/wild condition
    usage: /<command>
